### ISSUE TITLE
Only returns first 30 team members

### ISSUE THREAD

**Issue by bryangingechen** [garnertb/get-team-members#7]
We tested this action and found that the action only returns the first 30 members. The reason seems to be that `per_page` defaults to 30: https://docs.github.com/en/rest/teams/teams#list-teams

**Comment by garnertb** [comment]
Admittedly that's all I needed for my initial use case but I'll update the action to add pagination soon.

**Comment by garnertb** [comment]
Fixed in [2688ee4](https://github.com/garnertb/get-team-members/commit/2688ee41d3e30fae4bdf20c13e6d77b9d5b5200f).

**Comment by bryangingechen** [comment]
Thanks for the quick response! However, I just tried re-running the action and it's now failing with the following output:

> gh: HTTP 400
parse error: Invalid numeric literal at line 2, column 7
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Error: garnertb/get-team-members/v1/action.yml (Line: 43, Col: 12):
Error: The template is not valid. garnertb/get-team-members/v1/action.yml (Line: 43, Col: 12): Error reading JToken from JsonReader. Path '', line 0, position 0.

**Comment by garnertb** [comment]
🤦🏻 My bad, got that fixed, thanks for reporting.
